import assert from 'node:assert/strict';
import {blankWorkspace,type Listing} from '../lib/domain';
import {prepareChatComparison} from '../lib/chat-comparison';

const car=(id:string,price:number,fees=0)=>({id,title:id,price,fees,total:price+fees} as Listing);
const w=blankWorkspace();
w.filters.shippingAllowance=500;
w.listings=[car('expensive-first',40000),car('second',35000),car('third',30000),car('lowest',15000),car('fees-matter',14000,4000),car('middle',16000),{...car('discount',1000),priceWarning:'Savings, not asking price'},car('unknown',0)];
w.saved=[car('saved-from-old-search',5000)];
w.compare=['expensive-first'];w.comparisonCars=[w.listings[0]];
const reply=prepareChatComparison(w,'Compare the three cheapest cars');
assert.deepEqual(w.compare,['lowest','middle','fees-matter'],'rank all current results, exclude suspect prices and unrelated saved cars');
assert.equal(reply.target,'compare');
assert.match(reply.text,/\$15,500/,'use current shipping reserve and disclosed fees');
assert.equal(w.saved.length,1,'comparison does not change favorites');
assert.equal(w.listings.length,8,'comparison does not discard results');
assert.deepEqual(w.comparisonCars?.map(c=>c.id),w.compare);
assert.deepEqual(prepareChatComparison(w,'Compare the two cheapest selected cars').ids,['lowest','middle']);
assert.deepEqual(prepareChatComparison(w,'Compare my selected cars').ids,['lowest','middle']);
const empty=blankWorkspace();
empty.listings=[car('a',20000)];
assert.equal(prepareChatComparison(empty,'Compare my selected cars').target,undefined,'do not silently select different cars');
assert.deepEqual(empty.compare,[]);
assert.match(prepareChatComparison(empty,'Compare the cheapest cars').text,/Add another car/);
empty.listings=[{...car('bad',500),priceWarning:'Unconfirmed'}];
const prior=[...empty.compare];
assert.equal(prepareChatComparison(empty,'Compare the cheapest cars').target,undefined);
assert.deepEqual(empty.compare,prior,'an unavailable ranking does not erase the previous comparison');
console.log('PASS: comparisons rank all current results, retain exact selected cars, exclude bad prices, and populate Compare');
