import assert from 'node:assert/strict';
import {marketValue,highlightedDeals} from '../lib/market-value';
import {normalizeMarketcheck} from '../lib/marketcheck';
const now=Date.parse('2026-09-19T12:00:00Z');
const car=(i:number,price=30000)=>normalizeMarketcheck({id:String(i),vdp_url:`https://dealer.example/car/${i}`,heading:'2022 BMW M3 Competition',inventory_type:'used',price,miles:40000,build:{make:'BMW',model:'M3',trim:'Competition',year:2022},dealer:{state:'CO'},last_seen_at_date:'2026-09-18T12:00:00Z'},false)!;
const target=car(0),pool=[28000,29000,30000,31000,32000].map((p,i)=>car(i+1,p));
const result=marketValue(target,pool,now);assert(result.available);assert.equal(result.low,29000);assert.equal(result.high,31000);assert.equal(result.median,30000);assert.equal(result.rating,'within');assert.equal(result.confidence,'Low');
assert(!marketValue({...target,price:999},pool,now).available,'payment-sized price cannot appear as a highlighted deal even without a provider warning');
assert(!marketValue({...target,sourceUpdatedAt:'2027-01-01'},pool,now).available,'future-dated inventory is not treated as fresh');
const low=marketValue({...target,price:27000},pool,now);assert(low.available);assert.equal(low.rating,'below');
const high=marketValue({...target,price:33000},pool,now);assert(high.available);assert.equal(high.rating,'above');
assert(!marketValue(target,pool.slice(0,4),now).available);
assert(!marketValue(target,[...pool.slice(0,4),{...pool[0],id:'duplicate'}],now).available,'same car cannot inflate sample');
assert(!marketValue(target,[target,...pool.slice(0,4)],now).available,'subject excluded');
for(const patch of [{trim:''},{seller:'unknown' as const},{priceWarning:'Payment'},{titleStatus:'salvage'},{sourceUpdatedAt:'2026-01-01'}])assert(!marketValue({...target,...patch},pool,now).available);
for(const patch of [{trim:'Base'},{seller:'private' as const},{year:2019},{miles:90000},{priceWarning:'Auction bid'},{sourceUpdatedAt:'2026-01-01'}])assert(!marketValue(target,pool.map(c=>({...c,...patch})),now).available);
const broad=marketValue(target,pool.map(c=>({...c,state:'NY'})),now);assert(broad.available);assert.equal(broad.regional,false);
const outliers=marketValue(target,[...pool,...[29500,30500,999999].map((p,i)=>car(i+6,p))],now);assert(outliers.available);assert.equal(outliers.count,7);assert(outliers.high<32000);
console.log('PASS: market ranges, color thresholds, unique comparables, sparse data, stale prices and outliers');
const specified={...target,drive:'RWD',transmission:'Automatic',fuel:'Gasoline',bodyType:'Sedan'};
const aliases=pool.map(c=>({...c,drive:'Rear-wheel Drive',transmission:'8-Speed Automatic',fuel:'Unleaded',bodyType:'sedan'}));
assert(marketValue(specified,aliases,now).available,'equivalent source specification labels match');
for(const patch of [{drive:'AWD'},{transmission:'Manual'},{fuel:'Diesel'},{bodyType:'Coupe'}])assert(!marketValue(specified,aliases.map(c=>({...c,...patch})),now).available,'different specifications stay excluded');
const currentPool=pool.map(c=>({...c,checkedAt:new Date().toISOString(),sourceUpdatedAt:new Date().toISOString()}));
const deal={...target,id:'deal',price:27000,sourceUpdatedAt:new Date().toISOString()};
const pricey={...deal,id:'pricey',price:40000};
const unrated={...deal,id:'unrated',trim:''};
assert.deepEqual(highlightedDeals([unrated,pricey,deal],currentPool).map(c=>c.id),['deal','pricey','unrated'],'highlighted deals put supported lower prices first and unrated cars last');
