import assert from 'node:assert/strict';
import {healthyCursor,mergeSearch,mergeSources} from '../lib/search-session';
import {encodeWorkspace,decodeWorkspace} from '../lib/workspace-codec';
import {initialFilters,filterSchema,firstCursor,rank} from '../lib/domain';
import {normalizeMarketcheck,marketcheckUrl} from '../lib/marketcheck';
import {basic} from '../lib/basic-parser';
const car=(i:number)=>normalizeMarketcheck({id:String(i),vin:String(i).padStart(17,'0'),price:45000+i,vdp_url:`https://example.test/${i}`,base_ext_color:'Green',exterior_color:'Isle of Man Green Metallic',build:{make:'BMW',model:'M4',year:2023,trim:'Competition'},miles:12000},false)!;
const f=filterSchema.parse({make:'BMW',model:'M4',exteriorColor:'green'});
const merged=mergeSearch([car(1),car(2)],[car(2),car(3)],f);
const mislabeled={...car(70),price:7500,year:2010,miles:150000,evidenceText:'Savings $7,500. Full asking price $25,000.'};
assert.equal(mergeSearch([], [mislabeled], {...f,maxPrice:10000}).length,0,'marketplace-style imports are reviewed before the first budget match');
assert.equal(mergeSearch([mislabeled], [], {...f,maxPrice:10000}).length,0,'previously collected bad amounts cannot survive a follow-up');
assert(mergeSearch([], [mislabeled], f)[0].priceWarning,'unbudgeted browsing withholds the mislabeled amount');
const expired={...car(71),priceReview:{status:'matched' as const,checkedAt:new Date(Date.now()-25*3600000).toISOString(),reportedPrice:45071,sourcePrice:45071,note:'Previously checked'}};
assert.equal(mergeSearch([], [expired], {...f,maxPrice:50000}).length,0,'cached result checks must still be fresh when consumed');
assert.equal(merged.length,3,'later pages append and deduplicate instead of replacing results');
assert.equal(mergeSearch(merged,[{...car(2),price:42000}],f).find(r=>r.id===car(2).id)?.price,42000);
assert.equal(mergeSearch(merged,[{...car(4),exteriorColor:'Blue',baseExteriorColor:'Blue'}],f).length,3);
assert.equal(healthyCursor(firstCursor(),[{name:'dealer',status:'error',detail:'quota'}])?.dealer,null,'failed sources are not repeatedly retried automatically');
assert.equal(healthyCursor({dealer:50,private:null,auction:null,autodev:null},[{name:'dealer',status:'error',detail:'quota'}]),null);
const sources=mergeSources([{name:'dealer',status:'searched',detail:'first',inspected:50,total:120}],[{name:'dealer',status:'searched',detail:'next',inspected:50,total:120}]);
assert.equal(sources[0].inspected,100);assert.equal(sources[0].total,120);
const fresh=basic('find a green M4',filterSchema.parse({make:'Ford',model:'F-150',bodyType:'pickup',cabStyle:'crew',drivetrain:'4wd',maxPrice:35000}));
assert.equal(fresh.filters.model,'M4');assert.equal(fresh.filters.cabStyle,'');assert.equal(fresh.filters.bodyType,'');assert.equal(fresh.filters.maxPrice,null);
assert.equal(marketcheckUrl({...f,exteriorColor:'Isle of Man Green'},false).searchParams.get('exterior_color'),'Isle of Man Green');
assert.equal(mergeSearch([], [car(1)], {...f,exteriorColor:'Isle of Man Green'}).length,1);
assert.equal(filterSchema.parse({make:'Morgan',model:'Plus Six',trim:'Bespoke edition'}).trim,'Bespoke edition','manual entries are not restricted to the suggestion catalogue');
let repeatedlyRanked=[car(1)];for(let i=0;i<20;i++)repeatedlyRanked=rank(repeatedlyRanked,repeatedlyRanked,initialFilters,100);
assert(repeatedlyRanked[0].concerns.length<10,'reading accumulated results does not endlessly duplicate concerns');
const large={listings:Array.from({length:3000},(_,i)=>car(i)),filters:f};
const packed=await encodeWorkspace(large);assert(packed.startsWith('gzip:'));assert(packed.length<1500000);assert.deepEqual(await decodeWorkspace(packed),large);
assert.deepEqual(await decodeWorkspace(JSON.stringify({listings:[]})),{listings:[]},'existing workspaces remain readable');
console.log('PASS: accumulation, duplicate updates, hard filters, failed-source stopping, fresh M4 search, freeform vehicles, exact paint and 3,000-car storage');
