import {config,db} from './server';
export type Provider='marketcheck'|'openai'|'autodev'|'apify';
const enc=new TextEncoder();
const from64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const to64=(b:Uint8Array)=>btoa(String.fromCharCode(...b));
async function key(){const raw=config().CONNECTION_ENCRYPTION_KEY;if(!raw)throw Error('Secure connection storage is unavailable. Please try later.');return crypto.subtle.importKey('raw',from64(raw),{name:'AES-GCM'},false,['encrypt','decrypt'])}
export async function storeKey(userId:string,provider:Provider,value:string){const iv=crypto.getRandomValues(new Uint8Array(12));const bytes=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode(userId+':'+provider)},await key(),enc.encode(value));await db().prepare('INSERT INTO connections(user_id,provider,encrypted_key,checked_at) VALUES(?,?,?,?) ON CONFLICT(user_id,provider) DO UPDATE SET encrypted_key=excluded.encrypted_key,checked_at=excluded.checked_at').bind(userId,provider,to64(iv)+'.'+to64(new Uint8Array(bytes)),Date.now()).run()}
export async function providerKey(userId:string,provider:Provider){const row=await db().prepare('SELECT encrypted_key FROM connections WHERE user_id=? AND provider=?').bind(userId,provider).first<{encrypted_key:string}>();if(!row)return config()[provider==='marketcheck'?'MARKETCHECK_API_KEY':provider==='autodev'?'AUTODEV_API_KEY':provider==='apify'?'APIFY_API_KEY':'OPENAI_API_KEY'] as string|undefined;const [iv,cipher]=row.encrypted_key.split('.');const out=await crypto.subtle.decrypt({name:'AES-GCM',iv:from64(iv),additionalData:enc.encode(userId+':'+provider)},await key(),from64(cipher));return new TextDecoder().decode(out)}
export const marketcheckKey=(id:string)=>providerKey(id,'marketcheck');
export async function connectionStatus(userId:string){const rows=await db().prepare('SELECT provider,checked_at FROM connections WHERE user_id=?').bind(userId).all<{provider:string;checked_at:number}>();const market=rows.results.find(r=>r.provider==='marketcheck'),openai=rows.results.find(r=>r.provider==='openai'),autodev=rows.results.find(r=>r.provider==='autodev');return {apify:rows.results.some(r=>r.provider==='apify')||!!config().APIFY_API_KEY,autodev:!!autodev||!!config().AUTODEV_API_KEY,autoCheckedAt:autodev?.checked_at??null,marketcheck:!!market||!!config().MARKETCHECK_API_KEY,openai:!!openai||!!config().OPENAI_API_KEY,checkedAt:market?.checked_at??null,aiCheckedAt:openai?.checked_at??null,secureSetupReady:!!config().CONNECTION_ENCRYPTION_KEY}}

export async function inventoryKeys(id:string){const [marketcheck,autodev]=await Promise.all([providerKey(id,'marketcheck'),providerKey(id,'autodev')]);return {marketcheck,autodev}}
